name: Test

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: npm ci
      - name: Unit test
        run: npm test
        env:
          CI: true